window.ENV = {
  USER_SERVICE_URL: "${USER_SERVICE_URL}",
  SESSION_SERVICE_URL: "${SESSION_SERVICE_URL}",
  SESSION_SERVICE_WS_URL: "${SESSION_SERVICE_WS_URL}",
  MATCHMAKER_SERVICE_URL: "${MATCHMAKER_SERVICE_URL}",
  GAME_DEV_URL: "${GAME_DEV_URL}",
};
